spring.application.name=demo
spring.datasource.url=jdbc:postgresql://ep-lucky-wave-adx8p0o5-pooler.c-2.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_Of8RnQsJ2xdm&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Of8RnQsJ2xdm
spring.jpa.hibernate.ddl-auto=update
